# Generated by Django 6.0.1 on 2026-01-29 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('class_level', models.CharField(max_length=50)),
                ('due_date', models.DateTimeField()),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_text', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'assignment_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Class Test'), ('midterm', 'Mid-Term Exam'), ('final', 'Final Exam'), ('mock', 'Mock Exam')], max_length=20)),
                ('classes', models.JSONField(default=list, help_text="List of class levels or ['all']")),
                ('subjects', models.JSONField(default=list, help_text="List of subjects or ['all']")),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateField(help_text='Exam start date')),
                ('end_date', models.DateField(help_text='Exam end date')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('submission_type', models.CharField(choices=[('questions', 'Question Paper'), ('grades', 'Grade Sheet')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_submissions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('grade_letter', models.CharField(blank=True, max_length=3)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['-exam__start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('class_level', models.CharField(max_length=50)),
                ('section', models.CharField(choices=[('grammar', 'Grammar'), ('technical', 'Technical'), ('commercial', 'Commercial')], default='grammar', max_length=20)),
                ('education_stream', models.CharField(blank=True, choices=[('grammar', 'Grammar'), ('technical', 'Technical'), ('commercial', 'Commercial')], max_length=20, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('art_or_science', models.CharField(blank=True, choices=[('arts', 'Arts'), ('science', 'Science')], max_length=10, null=True)),
                ('a_level_stream', models.CharField(blank=True, choices=[('A1', 'A1 - Arts with Languages'), ('A2', 'A2 - Arts with Social Sciences'), ('A3', 'A3 - Arts with Mathematics'), ('A4', 'A4 - Arts with Science'), ('S1', 'S1 - Physical Sciences'), ('S2', 'S2 - Biological Sciences'), ('S3', 'S3 - Mathematics & Computer Science'), ('S4', 'S4 - Engineering Sciences')], max_length=5, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['student_id'],
            },
        ),
    ]
