# Generated by Django 6.0.1 on 2026-01-29 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(default='Wisdom High School', max_length=255)),
                ('academic_year', models.CharField(default='2024/2025', max_length=20)),
                ('current_term', models.CharField(default='Term 1', max_length=20)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('two_factor_auth_required', models.BooleanField(default=False)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('last_backup_date', models.DateTimeField(blank=True, null=True)),
                ('last_cache_clear_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
