# Generated by Django 6.0.1 on 2026-01-29 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subjects', models.JSONField(default=list, help_text='List of subjects taught')),
                ('classes_assigned', models.JSONField(default=list, help_text='List of classes assigned to teach')),
                ('hours_per_week', models.IntegerField(default=0, help_text='Number of teaching hours per week')),
            ],
            options={
                'db_table': 'teachers',
                'ordering': ['teacher_id'],
            },
        ),
    ]
